# Generated by Django 5.2.1 on 2025-06-04 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='MeatsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meets_name', models.CharField(max_length=32, verbose_name='название')),
                ('price', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вес продукта (в кг)')),
                ('expiration_period', models.IntegerField(default=10, verbose_name='срок годности в днях')),
                ('composition', models.TextField(verbose_name='состав')),
                ('storage_condition', models.TextField(verbose_name='условия хранение')),
                ('packaging', models.TextField(verbose_name='упаковка')),
                ('equipment', models.TextField(blank=True, null=True, verbose_name='коплектация')),
                ('image', models.ImageField(blank=True, null=True, upload_to='meats_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_meats', to='halal_app.category')),
            ],
            options={
                'verbose_name_plural': 'Мясные продукты',
            },
        ),
    ]
