# Generated by Django 5.1.6 on 2025-04-26 06:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Администратор',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, null=True, upload_to='buyer_images/')),
            ],
            options={
                'verbose_name_plural': 'Покупатель',
            },
            bases=('halal_app.userprofile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('created_moth', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketer_images/')),
            ],
            options={
                'verbose_name_plural': 'Продавец',
            },
            bases=('halal_app.userprofile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BirdProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bird_name', models.CharField(max_length=32, verbose_name='название')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('expiration_period', models.IntegerField(default=10, verbose_name='Срок годности')),
                ('composition', models.TextField(blank=True, null=True, verbose_name='состав')),
                ('storage_conditions', models.TextField(verbose_name='Условия хранения, от 0 до +4°C')),
                ('packaging', models.TextField(verbose_name='Упаковка')),
                ('equipment', models.TextField(blank=True, null=True, verbose_name='комлектация')),
                ('price', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bird_images/')),
                ('created_date', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bird_eggs', to='halal_app.category', verbose_name='мясо птицы и яйца')),
            ],
            options={
                'verbose_name_plural': 'Мясо птицы и яйца',
            },
        ),
        migrations.CreateModel(
            name='BakeryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakery_name', models.CharField(max_length=32, verbose_name='выпечка название')),
                ('image', models.ImageField(upload_to='image_bakery')),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='вес')),
                ('expiration_date', models.DateField(verbose_name='срока годности')),
                ('created_date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bakery_category', to='halal_app.category')),
            ],
            options={
                'verbose_name_plural': 'Мука, хлеб и выпечка',
            },
        ),
        migrations.CreateModel(
            name='BabyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=32, verbose_name='название товары')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bady_images/')),
                ('created_date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baby_category', to='halal_app.category')),
            ],
            options={
                'verbose_name_plural': 'Товары для детей',
            },
        ),
        migrations.CreateModel(
            name='ConfectioneryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=32, verbose_name='Кондитерское название')),
                ('image', models.ImageField(upload_to='image_cake')),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='вес')),
                ('expiration_date', models.DateField(verbose_name='срока годности')),
                ('created_date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_cake', to='halal_app.category')),
            ],
            options={
                'verbose_name_plural': 'Кондитерские изделия',
            },
        ),
        migrations.CreateModel(
            name='Dairy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dairy_name', models.CharField(max_length=32, verbose_name='молочные продукты')),
                ('image', models.ImageField(upload_to='dairy_image')),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='вес')),
                ('expiration_date', models.DateField(verbose_name='срока годности')),
                ('created_date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dairy_category', to='halal_app.category')),
            ],
            options={
                'verbose_name_plural': ' Молочные продукты',
            },
        ),
        migrations.CreateModel(
            name='DrinkProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=100, verbose_name='Название напитка')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Объем напитка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='drink_images/')),
                ('created_date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drink_category', to='halal_app.category')),
            ],
            options={
                'verbose_name_plural': 'Напитки',
            },
        ),
        migrations.CreateModel(
            name='FishProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_name', models.CharField(max_length=32)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('expiration_period', models.IntegerField(default=10, verbose_name='Срок годности')),
                ('composition', models.TextField(blank=True, null=True, verbose_name='состав')),
                ('storage_conditions', models.TextField(verbose_name='Условия хранения, от 0 до +4°C')),
                ('packaging', models.TextField(verbose_name='Упаковка')),
                ('equipment', models.TextField(blank=True, null=True, verbose_name='комлектация')),
                ('price', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fish_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_products', to='halal_app.category')),
            ],
            options={
                'verbose_name_plural': 'Рыба и морепродукты',
            },
        ),
        migrations.CreateModel(
            name='FrozenProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frozen_name', models.CharField(max_length=32, verbose_name='замороженные продукты')),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('frozen_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='frozen_images/')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='вес')),
                ('created_date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frozen_category', to='halal_app.category')),
            ],
            options={
                'verbose_name_plural': 'Замороженные продукты',
            },
        ),
        migrations.CreateModel(
            name='GrocerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocer_name', models.CharField(max_length=32, verbose_name='название продукты')),
                ('image', models.ImageField(upload_to='image_grocery')),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='вес')),
                ('expiration_date', models.DateField(verbose_name='срока годности')),
                ('created_date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_category', to='halal_app.category')),
            ],
            options={
                'verbose_name_plural': 'Бакалея',
            },
        ),
        migrations.CreateModel(
            name='HealthBeauty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='название товара')),
                ('image', models.ImageField(blank=True, null=True, upload_to='beauty_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_date', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beauty_category', to='halal_app.category')),
            ],
            options={
                'verbose_name_plural': 'Здоровье и красота',
            },
        ),
        migrations.CreateModel(
            name='HomeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='товары для дома')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_date', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_category', to='halal_app.category')),
            ],
            options={
                'verbose_name_plural': 'Товары для дома',
            },
        ),
        migrations.CreateModel(
            name='MeatsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meets_name', models.CharField(max_length=32, verbose_name='название')),
                ('price', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вес продукта (в кг)')),
                ('expiration_period', models.IntegerField(default=10, verbose_name='срок годности в днях')),
                ('composition', models.TextField(verbose_name='состав')),
                ('storage_condition', models.TextField(verbose_name='условия хранение')),
                ('packaging', models.TextField(verbose_name='упаковка')),
                ('equipment', models.TextField(blank=True, null=True, verbose_name='коплектация')),
                ('image', models.ImageField(blank=True, null=True, upload_to='meats_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_meats', to='halal_app.category')),
            ],
            options={
                'verbose_name_plural': 'Мясные продукты',
            },
        ),
        migrations.CreateModel(
            name='Pharmaceutical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='название лекарств')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicine_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_date', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_category', to='halal_app.category')),
            ],
            options={
                'verbose_name_plural': 'Фармацевтика',
            },
        ),
        migrations.CreateModel(
            name='ReadyMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=32, verbose_name='название продукты')),
                ('image', models.ImageField(upload_to='image_ready')),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='вес')),
                ('expiration_date', models.DateField(verbose_name='срока годности')),
                ('created_date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ready_category', to='halal_app.category')),
            ],
            options={
                'verbose_name_plural': 'Готовая еда',
            },
        ),
        migrations.CreateModel(
            name='Vitamins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='название витамины')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vitamins_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_date', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitamins_category', to='halal_app.category')),
            ],
            options={
                'verbose_name_plural': 'Бад и витамины',
            },
        ),
    ]
