# Generated by Django 5.1.6 on 2025-06-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halal_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
    ]
