# Generated by Django 5.1.6 on 2025-04-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категория'},
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='price',
        ),
    ]
