# Generated by Django 5.1.6 on 2025-06-09 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_buyer_image_remove_buyer_user'),
        ('halal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_carts', to='accounts.buyer'),
        ),
        migrations.AlterField(
            model_name='save',
            name='user_save',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_saves', to='accounts.buyer'),
        ),
    ]
