# Generated by Django 5.1.6 on 2025-06-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halal_app', '0002_rename_name_brand_brand_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, null=True, verbose_name='состав'),
        ),
        migrations.AddField(
            model_name='product',
            name='equipment',
            field=models.TextField(blank=True, null=True, verbose_name='комплектация'),
        ),
        migrations.AddField(
            model_name='product',
            name='expiration_period',
            field=models.PositiveIntegerField(default=12, verbose_name='срок годности'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='количество'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_condition',
            field=models.TextField(blank=True, null=True, verbose_name='условия хранение'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Вес продукта (в кг)'),
        ),
    ]
