# Generated by Django 5.1.6 on 2025-04-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halal_app', '0002_alter_category_options_remove_buyer_buyer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesman',
            name='description',
        ),
        migrations.RemoveField(
            model_name='salesman',
            name='marketer_name',
        ),
    ]
