# Generated by Django 5.1.6 on 2025-06-11 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_buyer_image_remove_buyer_user'),
        ('halal_app', '0002_alter_cart_user_cart_alter_save_user_save'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user_cart',)},
        ),
        migrations.AlterUniqueTogether(
            name='save',
            unique_together={('user_save',)},
        ),
    ]
