# Generated by Django 5.1.6 on 2025-06-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halal_app', '0003_alter_cart_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveitem',
            old_name='save',
            new_name='save_obj',
        ),
    ]
