# Generated by Django 5.1.6 on 2025-04-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halal_app', '0003_remove_salesman_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesman',
            name='market_image',
        ),
    ]
