# Generated by Django 5.1.6 on 2025-06-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halal_app', '0003_remove_product_stock_product_composition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default=1, upload_to='category_images/'),
            preserve_default=False,
        ),
    ]
