# Generated by Django 5.1.6 on 2025-06-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halal_app', '0004_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_period',
            field=models.PositiveIntegerField(blank=True, default=12, null=True, verbose_name='срок годности'),
        ),
    ]
