# Generated by Django 5.1.6 on 2025-06-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halal_app', '0004_rename_save_saveitem_save_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('Доставлено', 'Доставлено'), ('в пути', 'в пути'), ('в ожидании', 'в ожидании'), ('отменен', 'отменен')], default=1, max_length=34),
            preserve_default=False,
        ),
    ]
