# Generated by Django 5.1.6 on 2025-06-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='user',
        ),
    ]
