# Generated by Django 5.2.1 on 2025-06-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_buyer_image_remove_buyer_user'),
        ('halal_app', '0005_cartitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesman',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='salesman',
            name='created_moth',
        ),
        migrations.AddField(
            model_name='salesman',
            name='categories',
            field=models.ManyToManyField(to='halal_app.category'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='name_shop',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
